#+title: Homl

* 2 глава
- распределение ошибок обученной модели
- интервальная оценка ошибки, доверительный интервал
- l1 функция потерь нестабильна (модель получается без единого стабильного решения)
- l2 функция потерь наказывает выбросы (модель сильно меняется при наличии выбросов)
- Преобразование Бокса-Кокса (https://habr.com/ru/articles/695556/, https://habr.com/ru/articles/690414/)
        Правила преобразования данных к нормальному закону возможны самые разные
        (степенное, логарифмическое, обратное, обратного корня и т.д.) [14, с.39] в
        зависимости от асимметрии исходного распределения.
        Г.Бокс и Д.Кокс предложили (Box, G. E. P.; Cox, D. R. An analysis of
        transformations. (With discussion). J. Roy. Statist. Soc. Ser. B 26 (1964),
        211–252. https://mathscinet.ams.org/mathscinet-getitem?mr=192611) более
        формализованную процедуру.
- Predictive power score (PPS) — это нормализованная метрика, которая
  показывает, в какой степени можно использовать одну переменную для
  предсказания другой.
  Значения PPS варьируются от 0 до 1.Особенности PPS:
  - Обнаруживает линейные и нелинейные взаимосвязи.
  - Может работать с категориальными данными.
  - Понимает асимметричные отношения, где переменная A влияет на переменную B
    больше, чем переменная B влияет на переменную A.
- Избегай inplace=True, так как функция не возвращает объект. В таком случае возникают проблемы с пайплайном
* 3 глава
- Softmax функция -- обобщение логистической регрессии для многоклассовой классификации

* 4 глава

* 5 глава
- margin -- зазор
- C -- это гиперпараметр мягкого зазора. Обратный коэффициент регуляризации ɑ
- выбор ядра зависит от данных
- для Гаусова ядра: gamma
- хорошее объяснение ядрового трюка на видео

* 8 глава
- Plotly https://plotly.com/python/
- UMAP
- How to Use t-SNE Effectively https://distill.pub/2016/misread-tsne/
